const LibreriaConstantes = {
    // Constantes de Uso
    OPERACIONPAGO: 'Pago',
    OPERACIONCONSULTA: 'Consulta',
    DIRECTORIOPUBLICO: 'public',
    DIRECTORIOTEMPORAL: '/tmp/',
    PROCESOCONSULTA: 'consultaInicial.js',
    PROCESOPAGO: 'realizaPago.js',
    TIMERCONSULTA: 'timerEjecucion.js',
    TIMERPAGO: 'timerPago.js',
    PROCESOINICIAL: 'child',
    PROCESOPARALELO: 'child1',
    PROCESOEXITOSO: 'successfully-CJ',
    BASEENLINEA: 'Database online',
    TIPOTOKEN: 'Bearer',
    SALIDAPROCESO: 'exit', 
    ERRORPROCESO: 'error',
    UNICOCLIENTE: 'client-secret',
    UNICOINICIAL: 'client_id',
    UNICOINICIALINSTI: 'client_secret',
    UNICOINSTITUCION: 'client-id',
    NUMEROTRANSACCION: 'numero-transaccion',
    UNICOTOKEN: 'Token',
    CEDULACLIENTE: 'counterPart',
    TOKENTRANSACCION: 'Authorization',
    FINPRINCIPAL: 'Child process principal exited with code: ',
    COMPROBANTE: 'Nro Comprobante',
    NOMBRECOMPLETO: 'NOMBRE COMPLETO',
    JOURNAL: 'JOURNAL ID',
    PRODUCTO: 'PRODUCTO',
    FLAGCABECERA: 'CABECERA',
    FLAGDETALLE: 'DETALLE',
    FLAGNINGUNO: 'NINGUNO',
    RECIBEPRINCIPAL: 'Child process received message: ',
    RECIBETIMER: 'Child process received message:',
    FINTIMER: 'Child process exited with code: ',
    ERRORPRINCIPAL: 'Failed to start principal child process: ',
    ERRORTIMER: 'Failed to start principal child process: ',
    ERRORTOKEN: 'No se pudo generar el token',
    ERRORDATABASE: 'mensaje de error capturado:',
    ERRORTIEMPOESPERA: 'Error 504: Gateway Timeout',
    TITULOPETICIONES: 'Too many requests',
    MUCHASPETICIONES: 'Too many requests in a short time, try again in 1 minute.',
    SPFALLIDOMENS: 'Error, SP no accesible o no encontrado',
    MENSAJETIMER: 'Ejecuta consulta',
    PUERTODELSERVIDOR: 'Servidor corriendo en puerto',
    MENSAJEPAGO: 'Ejecuta Pago',
    MENJASEPROCESO: 'Ejecuta el Timer',
    TERMINATIMER: 'Termina Timer',
    MENSAGEGENERAL: 'message',
    REQUERIDOSI: 'true',
    REQUERIDONO: 'false',
    DESCRIPCIONPETICION: 'CODIGOPETICIONES',
    CODIGOPETICIONES: '10',
    CODIGOEXITOSO: '1',
    SPEXITOSO: '100',
    PAGOEXITOSO: '111',
    FALTADATO: '400',
    FALTADATOTOKEN: '114',
    SPFALLIDO: '116',
    ERRORGENERACION: '0000',
    VALIDEZTOKEN: '700s',
    CODCASTIGADO: '001',

    // constantes enteras
    CODIGOINSTITUCION: 3,
    VALORENERROR: 0,

    // ejecucion de procesos
    EJECUTORLOG: 'exec interfaz.sp_ws_insertar_transacciones',
    EJECUTACONSULTA: 'exec Interfaz.sp_ws_pichincha_consulta_credito',
    EJECUTAPAGO: 'exec Interfaz.sp_ws_pichincha_pago',
    PRUEBARAMA: 'prueba de commit desde rama DEV a PRINCIPAL'
}

module.exports= {
    LibreriaConstantes,
}